steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/notesbe-129-akbar", "."]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/notesbe-129-akbar"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "notesbe-129-akbar",
        "--image",
        "gcr.io/$PROJECT_ID/notesbe-129-akbar",
        "--timeout",
        "1000s",
        "--port",
        "5002",  # <-- sesuaikan dengan port di app dan dockerfile
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
